FROM node:14

WORKDIR /app

COPY package.json ./
COPY *.js ./
COPY src ./src/

ENV GATSBY_FRONTEND_URL=https://kylefrominternet.herokuapp.com

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN npm -g install gatsby-cli
RUN npm i
RUN npm run build

EXPOSE 9000

CMD gatsby serve -H 0.0.0.0 -p $PORT