FROM node:14

WORKDIR /app

COPY package.json ./
COPY *.js ./
COPY src ./src/

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN npm -g install gatsby-cli
RUN npm i
RUN npm run build

EXPOSE 9000

CMD gatsby serve -H 0.0.0.0 --bind 0.0.0.0:$PORT wsgi